# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: landing-page-db
    restart: always
    environment:
      # --- ATENÇÃO: Defina sua senha aqui ---
      POSTGRES_USER: user_blog
      POSTGRES_PASSWORD: vlCwMw5i1806#
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: